# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 260, 111, 48))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 260, 101, 48))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 260, 191, 48))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 320, 111, 48))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 320, 101, 48))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 320, 101, 48))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 320, 85, 48))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 380, 111, 48))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 380, 101, 48))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 380, 101, 48))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(360, 380, 85, 48))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 440, 111, 48))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(140, 440, 101, 48))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(250, 440, 101, 48))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(360, 440, 85, 48))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_15.setAutoRepeatInterval(100)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 500, 111, 48))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 500, 101, 48))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(250, 500, 101, 48))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(360, 500, 85, 48))
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: rgb(147, 147, 147); \n"
"    border-radius:20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(36, 60, 411, 161))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label.setStyleSheet("QLabel { \n"
"border:2px solid black;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CALCULATOR"))
        self.pushButton.setText(_translate("MainWindow", "OFF"))
        self.pushButton_2.setText(_translate("MainWindow", "BackSpace"))
        self.pushButton_3.setText(_translate("MainWindow", "+"))
        self.pushButton_4.setText(_translate("MainWindow", "1"))
        self.pushButton_5.setText(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "3"))
        self.pushButton_7.setText(_translate("MainWindow", "Clear"))
        self.pushButton_8.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "5"))
        self.pushButton_10.setText(_translate("MainWindow", "6"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.pushButton_12.setText(_translate("MainWindow", "7"))
        self.pushButton_13.setText(_translate("MainWindow", "8"))
        self.pushButton_14.setText(_translate("MainWindow", "9"))
        self.pushButton_15.setText(_translate("MainWindow", "×"))
        self.pushButton_16.setText(_translate("MainWindow", "."))
        self.pushButton_17.setText(_translate("MainWindow", "0"))
        self.pushButton_18.setText(_translate("MainWindow", "="))
        self.pushButton_19.setText(_translate("MainWindow", "÷"))
        self.label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
